### PR TITLE
Added ding mobile and needed contrib modules to ding make file

### PR DESCRIPTION
**Pull request by cableman**
As this extension requires contributed modules, I think it should be part of the drush make file.

### CODE REVIEW

**Comment by kasperg** [comment]
Should ding_mobile, alternator etc. be a part of the default distribution?

**Comment by cableman** [comment]
I think that mobile support is an important part of having a library site and should be part of the default distribution.

**Comment by kasperg** [comment]
OK.  Should we make it a part of 1.7.0?

On one hand I'm a bit worried about scope and time to test. On the other hand: If the modules are not enabled by default perhaps it does not need immediate testing.

**Comment by cableman** [comment]
We (aakb) will have to test them to ensure that the mobile site works with the new search result changes. But we could wait to the next release to include them in the build or wait until we have tested them.

**Comment by kasperg** [comment]
Then I guess that depends on when you will do the test :).

**Comment by cableman** [comment]
I think that we have be running the mobile site for some time now and this should be merge in. As you said Kasper they are not enabled by default

**Comment by kasperg** [comment]
How about adding a `ding_mobile.make` file containing the dependencies instead of declaring them here?

This creates a simpler and more clean ding.make.

**Pull request closed without merging**
