### PR TITLE
Refactoring of ding-deploy to resemble an install profile.

### PR DESCRIPTION
**Pull request by mikl**
This is the aforemetioned refactoring. I've cleaned up the branch I did it on, so it's diffable on Github :)

### CODE REVIEW

**Comment by mikl** [comment]
Jeg har i øvrigt testet det på KKBs miljø, og staging er deployed via denne refactor-branch. Det virkede uden at skulle ændre noget på serveren :)

**Comment by mikl** [comment]
Hey @kasperg, hvad siger du til det?

**Comment by kasperg** [comment]
Det lyder godt, men jeg har stadig virkelig travlt :(.

**Comment by kasperg** [comment]
I see no problem in merging this.

However [a bug in the fabfile](https://github.com/dingproject/ding-deploy/commit/526467efc157740e34a37649f35d719aa1fd9204#commitcomment-454927) prevents us from using this in production.

**Comment by cableman** [comment]
The pull can not be merged any more as the code have changed

**Comment by mikl** [comment]
Of course it can, it just can't merged automatically. A manual merge should be fairly easy to do.

**Pull request merged**
