### PR TITLE
Added the new ting fulltext module to the build

### PR DESCRIPTION
**Pull request by cableman**
I have added the new fulltext module to the makefile, so publisher descriptions are possible.

We many need to make an update function to ting_search that enables it as well ?

### CODE REVIEW

**Comment by kasperg** [comment]
Can we get a proper tag on the repo to keep track of things?

**Comment by cableman** [comment]
I have not tagged it as I think it should first be tagged, when we are ready to do the next release and updates the make file.

**Comment by kasperg** [comment]
So will versioning match Ding (1.9.0) or have it's own track (1.0.0)?

Either way I think it would be nice to have an indication on the repo regarding when it considered stable enough to be added to the project.

@mikl?

**Comment by mikl** [comment]
> So will versioning match Ding (1.9.0) or have it's own track (1.0.0)?

Either way works for me :+1:

**Comment by cableman** [comment]
I think we should match ding (1.9.0). I know that the plan was to make a 1.8.1 release, but as this creates a larger change we should skip 1.8.1 and go for 1.9.0.

**Comment by kasperg** [comment]
I've set the milestone accordingly.

**Pull request closed without merging**
