### PR TITLE
Updated sync_from_prod commando

### PR DESCRIPTION
**Pull request by cableman**
This pull request fixes some issue I had in the last deployment of aakb.

First fix is in the stg check before syncing database, which prevented roles such as "xxx:stg" form during a sync. 

I have changed the database dump and load calls to use drush, mostly because I use other database names then the ones in the script. I have also another files location and I use drush to locate the file path.

### CODE REVIEW

**Comment by kasperg** [comment]
Drush integration seems like a good solution. Let's use the tools we already have at hand!

**Comment by cableman** [comment]
This is not just a reformatting, the most important bit is the it allows "xxx:stg" roles to sync from prod and not just the "stg" role.

**Comment by cableman** [comment]
The role is not assign if there is a project, which there have to be. I run it like this: fab -r aakb:stg sync_from_prod:aakb

The role at <a href="https://github.com/dingproject/ding-deploy/blob/master/fabfile.py#L91">L91</a> is aakb:stg !

**Comment by kasperg** [comment]
Regarding formatting [the change is parsing already seems to be included in the first commit](https://github.com/cableman/ding-deploy/commit/86dac3a04039c830c1b98819657f8956cf3f4f13#L0R91).

The problem with L91 vs. your command is the double referencing of the project ind the command. The confusion is rooted in the introduction of environments in roles e.g. -R helsbib:stg as opposed to arguments sync_from_prod:helsbib

As AAKB is one of the "old" projects - like KKB - the command should be run in the old style: `fab -r stg sync_from_prod:aakb`.

Libraries which have been introduced later on should use `fab -r helsbib:stg sync_from_prod`.

**Pull request closed without merging**
