### PR TITLE
added missing dependencies

### PR DESCRIPTION
**Pull request by mrbase**
gmap and keys was missing in the ding.make file.
installing via ding's install profile - the installation failed due to the missing modules

### CODE REVIEW

**Comment by kasperg** [comment]
Actually the problem not with missing dependencies but an obsolete make file. @mikl replaced [gmap and keys with openlayers](https://github.com/dingproject/ding-deploy/commit/1e5dd9c8809f9fc3e3de81c1cc571c59081cbe21) and forgot to update the installation profile.

**Comment by mrbase** [comment]
so, we should wait for @mikl to update the profile and nuke our changes

**Comment by kasperg** [comment]
Or update the profile yourself and update the pull request :). The change should be trivial.

**Comment by mikl** [comment]
Wasn't planning on _nuking_ anyone's changes ;)

Sorry about the broken profile, I forgot it while I was working on the map thing :)

**Comment by mikl** [comment]
Ok, nu skulle det være fixet i profilen: 1430349afa0b76e29ddce51a8ad6e29f00490b7b :)

**Pull request closed without merging**
